import * as p from "@clack/prompts";
import pc from "picocolors";
import { loadPlugins } from "./registry";
import type { Workflow } from "./types";

async function main() {
  console.clear();

  p.intro(
    `${pc.bgRed(pc.black(" ZUKO "))} ${pc.bold("- Multi-Model Prompt Pipeline")}`,
  );

  const loaderPlugins = p.spinner();
  loaderPlugins.start("Loading available AI plugins...");
  const pluginsDisponibles = await loadPlugins();
  loaderPlugins.stop(
    `Ecosystem ready: ${pluginsDisponibles.size} plugins detected.`,
  );

  if (pluginsDisponibles.size === 0) {
    p.note(
      `No AI plugins found.\nInstall one by running: ${pc.cyan("bun install")}`,
      "Alert",
    );
  }

  // TODO: Load from workflow JSON file
  const workflow: Workflow = {
    id: "poc-flow",
    name: "Test Pipeline with Groq",
    description:
      "Three-stage prompt refinement pipeline with strict sequential output gating",
    nodes: [
      {
        id: "Engineer",
        pluginId: "groq",
        systemInstruction:
          "You are an expert Prompt Engineer. Take the raw request from the user and transform it into a highly structured, clear, and context-rich prompt. Define strict roles, constraints, and explicit requirements. Output ONLY the newly engineered prompt. Do not include introductions, explanations, or conversational meta-text.",
        fallbackPluginId: null,
      },
      {
        id: "QualityCheck",
        pluginId: "groq",
        systemInstruction:
          "You are a Senior QA Automation Engineer and Security Auditor. Review the structured prompt generated by the previous node. Fix any architectural ambiguities, add missing security safeguards (e.g., input sanitization constraints, error handling rules), and optimize its phrasing for performance. Output ONLY the audited and enhanced prompt text. Do not comment on what you changed or why.",
        fallbackPluginId: null,
      },
      {
        id: "FinalPolish",
        pluginId: "groq",
        systemInstruction:
          "You are a Principal Technical Writer. Take the audited prompt from the previous node and perform the ultimate syntax polish. Remove any lingering redundancies, streamline the language for absolute clarity, and format it cleanly with Markdown headers. Output ONLY the final production-ready prompt text. Any conversational commentary is strictly forbidden.",
        fallbackPluginId: null,
      },
    ],
  };

  const promptUser = await p.text({
    message: "Enter your base prompt or code to refine:",
    placeholder: "Type here...",
    validate(value) {
      if (value.length === 0) return "The prompt cannot be empty.";
    },
  });

  if (p.isCancel(promptUser)) {
    p.cancel("Operation cancelled safely.");
    process.exit(0);
  }

  // 4. Orchestration of the Graph
  let currentResult = promptUser;
  p.note(`Starting workflow execution: ${pc.green(workflow.name)}`);

  for (const node of workflow.nodes) {
    const plugin = pluginsDisponibles.get(node.pluginId);
    if (!plugin) {
      p.log.warn(
        `Skipping node ${node.id}: The plugin '${node.pluginId}' is not installed in the system.`,
      );
      continue;
    }

    const s = p.spinner();
    s.start(`Node ${node.id} -> Processing with ${pc.cyan(plugin.name)}...`);

    try {
      // Pass the accumulated result to the corresponding plugin
      currentResult = await plugin.execute(
        currentResult,
        node.systemInstruction,
      );
      s.stop(`Node ${node.id} completed.`);
    } catch (error: any) {
      s.stop(`Error in node ${node.id}`);
      p.cancel(
        `The workflow was interrupted due to an error: ${error.message}`,
      );
      process.exit(1);
    }
  }

  // 5. Print the final polished output of the entire pipeline
  p.outro(`${pc.bgGreen(pc.black(" FINAL RESULT "))} \n\n${currentResult}\n`);
}

main().catch((err) => {
  p.log.error(`Critical error during execution: ${err.message}`);
  process.exit(1);
});
